name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 1: Set up Node.js v22
      - name: Setup Node.js v22
        uses: actions/setup-node@v2
        with:
          node-version: '22'  # Node.js versiyasini 22 ga sozlash

      # Step 2: Install dependencies using npm
      - name: Install dependencies
        run: npm install  # npm yordamida barcha kerakli paketlarni o'rnatish

      # Step 3: Setup SSH and deploy
      - name: Setup SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Node.js versiyasini tekshirish
            node -v
            cd ~/arendum-api/
            git stash || { echo "git stash failed"; exit 1; }
            git pull origin main || { echo "git pull failed"; exit 1; }
            npm install  # npm yordamida o'rnatish
            npx prisma migrate deploy --name migrated  # Prisma migratsiya
            npx prisma generate  # Prisma fayllarini generatsiya qilish
            pm2 restart 0  # PM2 bilan qayta ishga tushirish

      # Step 4: Notify Telegram on success
      - name: Notify Telegram on success
        if: success()
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          COMMIT_AUTHOR=$(git log -1 --pretty=format:"%an")
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="CD Successfully.%0ACommit: $COMMIT_MESSAGE%0AAuthor: $COMMIT_AUTHOR"

      # Step 5: Notify Telegram on failure
      - name: Notify Telegram on failure
        if: failure()
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          COMMIT_AUTHOR=$(git log -1 --pretty=format:"%an")
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="CD Failed.\\nCommit: $COMMIT_MESSAGE\\nAuthor: $COMMIT_AUTHOR"
