name: CI

on:
  push:
    branches:
      - main # 'main' branchga push qilganda trigger bo'ladi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js v22
      - name: Set up Node.js v22
        uses: actions/setup-node@v3
        with:
          node-version: '22.12.0' # Node.js versiyasini 22.12.0 ga o'rnatish

      # Step 3: Install dependencies (using npm instead of pnpm)
      - name: Install dependencies
        run: |
          pnpm install # Kerakli paketlarni o'rnatish

      # Step 4: Run Tests
      - name: Run tests
        run: |
          pnpm test # Testlarni bajarish (agar testlar bo'lsa)

      # Step 5: Notify Telegram on success
      - name: Notify Telegram on success
        if: success()
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          COMMIT_AUTHOR=$(git log -1 --pretty=format:"%an")
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="CI Successfully.%0ACommit: $COMMIT_MESSAGE%0AAuthor: $COMMIT_AUTHOR"

      # Step 6: Notify Telegram on failure
      - name: Notify Telegram on failure
        if: failure()
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          COMMIT_AUTHOR=$(git log -1 --pretty=format:"%an")
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="CI Failed.\\nCommit: $COMMIT_MESSAGE\\nAuthor: $COMMIT_AUTHOR"
